
#
# ################################################################################
#   ## Copyright (C) Gaurav Dass - All Rights Reserved
#   ## Unauthorized copying of this file, via any medium is strictly prohibited
#   ## Proprietary and confidential
#   ## Written by Gaurav Dass <dassgaurav93@gmail.com>, January 2020
#
# ################################################################################

"""
Combined verbs
"""

verbs = ["spark",
"activate","activating",
"unleash",
"evoke","evoking",
"provoke","provoking",
"educe","educing",
"arouse","arousing",
"generate","generating",
"trigger",
"stimulate","stimulating",
"induce","inducing",
"produce",
"elicit",
"kindle","kindling",
"commence",
"instil",
"establish",
"occasion",
"perpetuate",
"actuate","actuating",
"facilitate","facilitating",
"engender",
"prompt",
"originate","originating",
"lead",
"provide",
"effectuate",
"cofound",
"provision",
"bringing",
"entail",
"indicate",
"initiating",
"inflect",
"evokes",
"effecting",
"result",
"causing",
"instigate",
"constitute",
"effect",
"causative",
"conduce to",
"in turn",
"for this reason",
"in consequence",
"consequent",
"originate in",
"consequential",
"bring about",
"consequently",
"as a consequence",
"eventuate in",
"resultant",
"set off",
"bring forth",
"kick up",
"contribute to",
"spark off",
"trigger off",
"stir up",
"set up",
"give birth to",
"put forward",
"call forth",
"fire up",
"bring on",
"give rise to",
"set in motion"]

reverse_verbs = ["stems from",
"stemmed from",
"brought on by",
"caused by",
"resulted from",
"results from",
"as a result of",
"in response to",
"because",
"on the grounds that",
"now that",
"owing to",
"on account of",
"due to"]
